spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.248.74.58:3306/smcc_cpro?useUnicode=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: smcc
    password: smcc2018
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 1
    maxActive: 20
    initialSize: 1
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000

