server:
  port: 8082
  context-path: /
  max-http-header-size: 102400
  undertow:
    io-threads: 2
    buffer-size: 1024
    direct-buffers: true
spring:
  profiles:
    active: dev,common
  freemarker:
    cache: false 
  application:
    name: Class-Protection
  http:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  thymeleaf:
    enabled: true
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true
    content-type: text/html
  # thymeleaf end
  messages:
    basename: /i18n/messages_en_US,i18n/messages_zh_CN
mybatis:
  mapperLocations: classpath*:mapper/*/*.xml
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    offset-as-page-num: true
    row-bounds-with-count: true
smcc.depends.ubs.api: http://10.248.65.107
cpro.api.url: http://10.246.146.156:8092/
appId: 907
redisId: 100
wildcard: 
    org: '@OWN_UNIT@'
    all: '@ALL_UNIT@'
    none: $none$