server:
  port: 8082
  context-path: /
  tomcat:
    accesslog:
      directory: ./logs
      enabled: true
logging:
  config: classpath:logback.xml
  path: ./logs
  level:
    root: info
spring:
  freemarker:
    cache: false 
  application:
    name: Class-Protection
  thymeleaf:
    enabled: true
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true
    content-type: text/html
  # thymeleaf end
  messages:
    basename: /i18n/messages_en_US,i18n/messages_zh_CN
mybatis:
  mapperLocations: classpath*:mapper/*/*.xml
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    offset-as-page-num: true
    row-bounds-with-count: true
smcc.depends.ubs.api: http://10.248.65.107
cpro.api.url: http://usmg.smcc.sinopec.com:8092/
appId: 907
redisId: 100
wildcard: 
    org: $org1$
    all: $all$
    none: $none$
